# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Doclavax
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Doclavax is a modern javadoc alternative

# the subpath of your site, e.g. /blog
baseurl: "/doclava"

# the base hostname & protocol for your site
url: "http://naghavi.me"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
